language: ruby
rvm:
- 2.3.0
- 2.2.4
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec/acceptance/*
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
